const namespaces = {
  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
  ex: "http://www.example.com/",
  tourism: "http://lddemo.mmlab.be/tourism/",
  skos: "http://www.w3.org/2004/02/skos/core#",
  foaf: "http://xmlns.com/foaf/0.1/",
  xsd: "http://www.w3.org/2001/XMLSchema#",
  schema: "http://schema.org/",
  ost: "http://w3id.org/ost/ns#",
  org: "http://www.w3.org/ns/org#",
  regorg: "http://www.w3.org/ns/regorg#",
  person: "http://www.w3.org/ns/person#",
  locn: "http://www.w3.org/ns/locn#",
  dcterms: "http://purl.org/dc/terms/",
  vcard: "http://www.w3.org/2006/vcard/ns#",
  adms: "http://www.w3.org/ns/adms#",
  oh: "http://semweb.mmlab.be/ns/oh#",
  time: "http://www.w3.org/2006/time#",
  prov: "http://www.w3.org/ns/prov#",
  csvw: "http://www.w3.org/ns/csvw#",
  gr: "http://purl.org/goodrelations/v1#",
  muto: "http://purl.org/muto/core#",
  acco: "http://purl.org/acco/ns#",
  combust: "http://combust.iminds.be/",
  oslo: "http://purl.org/oslo/ns/localgov/",
  tio: "http://purl.org/tio/ns#",
  "dbpedia-owl": "http://dbpedia.org/ontology/",
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
};

export { namespaces as default };
